source 'https://rubygems.org'

gem 'aasm'
gem 'active_admin_flat_skin'
gem 'active_interaction', '~> 3.6'
gem 'active_model_serializers'
gem 'activeadmin'
gem 'activeadmin_addons'
gem 'bootstrap'
gem 'bootstrap4-kaminari-views'
gem 'carrierwave', '1.2.2'
gem 'coffee-rails'
gem 'devise'
gem 'fog'
gem 'haml'
gem 'image_optim_pack'
gem 'image_optim_rails'
gem 'jquery-rails'
gem 'kaminari'
gem 'leaderboard'
gem 'listen', '~> 3.1.5'
gem 'mini_magick', '4.7.0'
gem 'mutations'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-vkontakte'
gem 'pg'
gem 'rails', '5.2.1'
gem 'redis'
gem 'rubocop'
gem 'sass-rails'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'select2-rails'
gem 'sidekiq'
gem 'turbolinks'
gem 'uglifier'

group :development, :test do
  gem 'byebug'
  gem 'spring'
  gem 'web-console', '3.5.1'
end
